version: '3'

services:

   mongo:
    image: mongo
    volumes:
      - db_data:/data/db
    restart: always

   elo7-challenge:
    build: .
    depends_on:
      - mongo
    image: python:3
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    restart: always
    command: bash -c "cd /usr/src/app; pip install --no-cache-dir -r requirements.txt; python app.py"

volumes:
    db_data: