version: '3'

services:

   mongo:
    image: mongo
    volumes:
      - db_data:/data/db
    restart: always

   elo7_challenge:
    build: .
    depends_on:
      - mongo
    image: elo7_challenge
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    restart: always

volumes:
    db_data: