version: '3'

services:

   mongo:
    image: mongo
    volumes:
      - db_data:/data/db
    restart: always

   elo7-challenge:
    build: .
    depends_on:
      - mongo
    image: elo7-challenge
    volumes:
      - ${WORKSPACE}:/usr/src/app
    ports:
      - "5000:5000"
    restart: always

volumes:
    db_data: